version: '3.4'

services:
  contosouniversity:
    image: ${DOCKER_REGISTRY-}contosouniversity
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - contosodb

  contosodb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: ContosoSqlDb
    restart: always
    environment:
      SA_PASSWORD: "pass%w0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
