version: '3.4'

services:
  contosouniversity:
    image: contosouniversity:dev
    container_name: ContosoUniversity
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ContosoUniversity"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
    volumes:
      - C:\Users\t.yuji\source\repos\ContosoDocker\ContosoDocker\ContosoUniversity:/app
      - C:\Users\t.yuji\source\repos\ContosoDocker\ContosoDocker\ContosoUniversity:/src
      - C:\Users\t.yuji\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\t.yuji\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Microsoft\Xamarin\NuGet\:/root/.nuget/fallbackpackages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages2:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages --additionalProbingPath /root/.nuget/fallbackpackages2  \"/app/bin/Debug/netcoreapp3.1/ContosoUniversity.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true